### ISSUE TITLE
The command "yarn" restores core-js v3.0+

### ISSUE THREAD

**Issue by gdlcf88** [zpfz/vuepress-creator#4]
I can only use the "node_modules" which is generated by `vuepress-creator ads myproject` since the command "yarn" restores core-js v3.0+ (the expected version is v2.6.11).

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/90323760-1cd58600-df98-11ea-91da-d3ba81d96c45.png)
`yarn add core-js@2` makes it work, but this problem should still be solved.

**Comment by zpfz** [comment]
I appreciate the reminder🌹🌹🌹. After debugging, I‘ve found the problem. To reduce the installation time, **vuepress-creator** does not install **vuepress** by default when installing **antdocs**, which causes the **core-js** version in **antdocs** to be overwritten by **vuepress** during `yarn install`. For now, I've solved the problem by modifying the template.

### Solution
Use the command line `vuepress-creator upgrade -t` to update the template at your terminal.
