### ISSUE TITLE
安装之后首页运行报错

### ISSUE THREAD

**Issue by fuyi501** [zpfz/vuepress-creator#9]
运行之后首页显示为空白，没有内容，看控制台报错，如下：

![image](https://user-images.githubusercontent.com/20770905/118388742-ca291780-b658-11eb-9ec6-b3c2ccf5fede.png)

![image](https://user-images.githubusercontent.com/20770905/118388737-b8477480-b658-11eb-9853-9baa432e1275.png)

**Comment by zpfz** [comment]
哦！近期 antdocs 主题做了一些变动，需要将首页的 README.md 中首页按钮配置进行修改，例：
```md
actionBtn:
  text: Get Started
  link: /guide/
  type: primary
  ghost: false
  size: large
preactionBtn:
  text: Playground
  link: /guide/
  type: primary
  ghost: true
  size: large
```

详情见：[首页按钮](https://antdocs.pages.dev/guide/extend-config.html#首页按钮)，另外 antdocs 近期更新详情见：[更新日志](https://antdocs.pages.dev/guide/changelog.html)

**Comment by fuyi501** [comment]
感谢，已经解决问题 :thumbsup: :thumbsup: :thumbsup:
